#pragma checksum "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\Error.cshtml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "078F086B88EAFD5691C500011AB8991D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1");

WriteLiteral(" class=\"error\"");

WriteLiteral(">Error.</h1>\r\n    <h2");

WriteLiteral(" class=\"error\"");

WriteLiteral(">An error occurred while processing your request.</h2>\r\n</hgroup>\r\n");

        }
    }
}
