//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.272")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_o0hem2vp {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_o0hem2vp() {
        }
        
        static object Create_ASP__Page_Views_Shared__Layout_cshtml() {
            return new ASP._Page_Views_Shared__Layout_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared_Error_cshtml() {
            return new ASP._Page_Views_Shared_Error_cshtml();
        }
        
        static object Create_ASP__Page_Views_Shared__LoginPartial_cshtml() {
            return new ASP._Page_Views_Shared__LoginPartial_cshtml();
        }
    }
}
