#pragma checksum "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9E21D3812F91C79B5D04D2632FF71CF0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__Layout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n    <head>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <title>");

            
            #line 5 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 162), Tuple.Create("\"", 182)
, Tuple.Create(Tuple.Create("", 169), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 169), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 241), Tuple.Create("\"", 326)
            
            #line 7 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 248), Tuple.Create<System.Object, System.Int32>(System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")
            
            #line default
            #line hidden
, 248), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 378), Tuple.Create("\"", 475)
            
            #line 8 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 385), Tuple.Create<System.Object, System.Int32>(System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")
            
            #line default
            #line hidden
, 385), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 529), Tuple.Create("\"", 598)
            
            #line 9 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 535), Tuple.Create<System.Object, System.Int32>(System.Web.Opti
            
            #line default
            #line hidden
, 535), false)
, Tuple.Create(Tuple.Create(" ", 551), Tuple.Create("mization.BundleTable.Bundles.ResolveBundleUrl(", 552), true)
);

WriteLiteral("~/Scripts/js\")\"></script>\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    </head>\r\n    <body>\r\n        <header>\r\n            <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(">");

            
            #line 16 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
                                     Write(Html.ActionLink("your logo here.", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\r\n                    <section");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 20 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
                   Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </section>\r\n                    <nav>\r\n                    " +
"    <ul");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\r\n                            <li>");

            
            #line 24 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 25 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            <li>");

            
            #line 26 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
                           Write(Html.ActionLink("Contact", "Contact", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        </ul>\r\n                    </nav>\r\n               " +
" </div>\r\n            </div>\r\n        </header>\r\n        <div");

WriteLiteral(" id=\"body\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 33 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
       Write(RenderSection("featured", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 35 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n        <footer>\r\n            <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n                    <p>&copy; ");

            
            #line 41 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_Layout.cshtml"
                         Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" id=\"social\"");

WriteLiteral(">\r\n                        <li><a");

WriteLiteral(" href=\"http://facebook.com\"");

WriteLiteral(" class=\"facebook\"");

WriteLiteral(">Facebook</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://twitter.com\"");

WriteLiteral(" class=\"twitter\"");

WriteLiteral(">Twitter</a></li>\r\n                    </ul>\r\n                </div>\r\n           " +
" </div>\r\n        </footer>\r\n    </body>\r\n</html>\r\n");

        }
    }
}
