#pragma checksum "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "27776A88EE9C97E83E9FEF031782C44E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Views_Shared__LoginPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__LoginPartial_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        Hello, ");

            
            #line 3 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
          Write(Html.ActionLink(User.Identity.Name, "ChangePassword", "Account", routeValues: null, htmlAttributes: new { @class = "username", title = "Change password" }));

            
            #line default
            #line hidden
WriteLiteral("!\r\n");

WriteLiteral("        ");

            
            #line 4 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
   Write(Html.ActionLink("Log off", "LogOff", "Account"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");

            
            #line 6 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("    <ul>\r\n        <li>");

            
            #line 8 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
       Write(Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", data_dialog_title = "Registration" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 9 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
       Write(Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", data_dialog_title = "Identification" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n");

            
            #line 11 "C:\Users\sarah\Desktop\DTFMVC3iA\solutionScripts\SolutionScriptUsage\Views\Shared\_LoginPartial.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
